import "./globals.css";
import Navbar from "../app/components/Navbar.jsx";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "codePlay72",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Navbar /> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
